# configuration for "master" branch
-
  image: Visual Studio 2017
  configuration: Release
  branches:
      only:
        - master
  version: 1.0.{build}
  environment:
    GITHUB_USERNAME:
      secure: 0Q9MvUId56SizmZwCf0cgg==
    GITHUB_TOKEN:
      secure: cDWUFbL2fl7VaypzZWe4FjJccQX6T4N+UV9bM9iJtByttr5RhxtOROi5/fvnmp2i
    NUGET_SOURCE: https://www.nuget.org/api/v2/package
    NUGET_APIKEY:
      secure: ELiBJuPIyjt3adBoySwp1ByTYk8IEUQSol07EzbDvOdhnxcSBmj3Itl4HPLtlbbG
  build_script:
  - ./build.cmd
  artifacts:
  - path: artifacts/*
  - path: '**/bin/*'
  test: off
  
# configuration for "develop" branch
-
  image: Visual Studio 2017
  configuration: Development
  branches:
      except:
          - master
  skip_branch_with_pr: true          
  version: 1.0.{build}
  environment:
    NUGET_SOURCE: https://www.myget.org/F/splat/api/v2/package
    NUGET_APIKEY:
      secure: bws/D/nus12zFcbVqDfVbB/ye23dMyM/7g52dezibJ28FTjtjudwEWvm0Y4NHVfb
  build_script:
  - ./build.cmd
  artifacts:
  - path: artifacts/*
  - path: '**/bin/*'
  test: off
