# configuration for "master" branch
-
  image: Visual Studio 2017
  configuration: Release
  branches:
    only:
      - master
  version: 1.0.{build}
  environment:
    GITHUB_USERNAME:
      secure: 0Q9MvUId56SizmZwCf0cgg==
    GITHUB_TOKEN:
      secure: R3xA9iMXfUUtFd3wuL38pcDa0/BjjpBvNcGShr5LRibZtBoOVSH47Jat75rwaGur
    NUGET_SOURCE: https://www.nuget.org/api/v2/package
    NUGET_APIKEY:
      secure: 0g2AqQxgiAIFhqoJbbmEPrJa15Z8U5xYT6vQe43Gocuxbjw74hBAIKbU+Cj65UNd
  build_script:
  - ./build.cmd
  artifacts:
  - path: artifacts/*
  - path: '**/bin/*'
  test: off
  
# configuration for "develop" branch
-
  image: Visual Studio 2017
  configuration: Development
  branches:
    except:
      - master
  on_finish:
    - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  version: 1.0.{build}
  environment:
    NUGET_SOURCE: https://www.myget.org/F/splat/api/v2/package
    NUGET_APIKEY:
      secure: YP/3KxC2ffsuHNaolPXj66JVGzSjON9FcR2S2OEzn9c6SV14oPzUh1ySyeT+G+aA
  build_script:
  - ./build.cmd
  artifacts:
  - path: artifacts/*
  - path: '**/bin/*'
  test: off
